USE [master]
GO

/****** Object:  Database [Scapegoat]    Script Date: 11/6/2021 11:59:29 AM ******/
DROP DATABASE [Scapegoat]
GO

/****** Object:  Database [Scapegoat]    Script Date: 11/6/2021 11:59:29 AM ******/
CREATE DATABASE [Scapegoat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scapegoat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Scapegoat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scapegoat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Scapegoat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scapegoat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Scapegoat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Scapegoat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Scapegoat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Scapegoat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Scapegoat] SET ARITHABORT OFF 
GO

ALTER DATABASE [Scapegoat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Scapegoat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Scapegoat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Scapegoat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Scapegoat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Scapegoat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Scapegoat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Scapegoat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Scapegoat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Scapegoat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Scapegoat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Scapegoat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Scapegoat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Scapegoat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Scapegoat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Scapegoat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Scapegoat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Scapegoat] SET RECOVERY FULL 
GO

ALTER DATABASE [Scapegoat] SET  MULTI_USER 
GO

ALTER DATABASE [Scapegoat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Scapegoat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Scapegoat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Scapegoat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Scapegoat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Scapegoat] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Scapegoat] SET  READ_WRITE 
GO

